### ISSUE TITLE
This will NOT work with Google Home 

### ISSUE THREAD

**Issue by highwingers** [OJ7/AdhanCast#3]
Your code only supports youtube caster controller, which will not cast on Audio Devices (Such as Google Home mini/Nest). I believe you tested your code on "ChromeCast" only.

**Comment by OJ7** [comment]
Just seeing this now. Tested this with google home and you are correct. It will only work with chromecast. I assumed it would work the same (esp since it seemed like the Home Assistant config I had used the same library). I will fix this inshaAllah.

**Comment by OJ7** [comment]
Pushed some changes to master. I've tested it and it should work fine now with Audio Devices. Please test it out to confirm. Thanks for bringing this up!

**Comment by highwingers** [comment]
I looked at the code, i see that you disabled youtube support for Audio Receivers. Looks good to me. Does it survive restarts? or after restart it need to schedule Adhans again?

**Comment by OJ7** [comment]
Thanks for looking over it!

This does not survive reboots. I have created #4 to address it.
